# Sorting, Counting, Subsetting

## Import libraries

In [4]:
## import libraries

import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [5]:
## import summer data
dfs = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv")
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [6]:
## import winter data

dfw = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv")
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

## Get a sense of the data

In [7]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.

dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [8]:
## WINTER
## what exactly do we have: columns, datatypes, etc.

dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

## Subsetting dataframes into smaller, targeted dataframes

When you subset a dataframe, you are filtering down based on selecting specific columns. We want to winnow a large dataset to manageable size by including only relevant columns.

There are two ways of doing this. One simple method is very common (you'll see many people use it), but the other method (also simple) is way more powerful and flexible.

### Method 1 - Pass a list of multiple column headers, it returns dataframe with only those columns
This is like calling a series (```df["Year"]```), but multiple columns:

####  ```df[["Column 1", "Column 2"]]```

In [9]:
## Create a dataframe that for only summer games years and cities

dfs_yr_city = dfs[["Year", "City"]]

dfs_yr_city

        Year            City
0       1896          Athina
1       1896          Athina
2       1896          Athina
3       1896          Athina
4       1896          Athina
...      ...             ...
222547  2016  Rio de Janeiro
222548  2016  Rio de Janeiro
222549  2016  Rio de Janeiro
222550  2016  Rio de Janeiro
222551  2016  Rio de Janeiro

[222552 rows x 2 columns]

## Sorting by single value

```dataframe.sort_values(by="Value 1", ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [10]:
## sort by athlete names A-Z for winter olympics

dfw.sort_values(by="Athlete Name", ascending = True)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
2788,56427,Aage Justesen,M,30.0,NaN,NaN,Denmark,DEN,1948,Sankt Moritz,Speed Skating,Speed Skating Men's 500 metres,NaN
15974,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,Speed Skating Women's 500 metres,NaN
15975,13348,"Aaltje Grietje ""Alie"" Boorsma",F,24.0,179.0,75.0,Netherlands,NED,1984,Sarajevo,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
3799,49758,Aarne Vin Edward Honkavaara,M,27.0,184.0,81.0,Finland,FIN,1952,Oslo,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
44053,12407,Aaron Blunck,M,17.0,180.0,78.0,United States,USA,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Halfpipe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15622,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
15623,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980,Lake Placid,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
8706,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
8705,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
8704,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968,Grenoble,Alpine Skiing,Alpine Skiing Men's Downhill,NaN

In [11]:
## sort city z-a

dfw.sort_values(by="City", ascending = False)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
39561,11951,Ole Einar Bjrndalen,M,36.0,178.0,65.0,Norway,NOR,2010,Vancouver,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,Gold
40747,52463,Marc Iselin,M,29.0,178.0,83.0,Switzerland,SUI,2010,Vancouver,Snowboarding,Snowboarding Men's Parallel Giant Slalom,NaN
40741,52316,Dmitry Gennadyevich Ipatov,M,25.0,176.0,60.0,Russia,RUS,2010,Vancouver,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
40742,52345,"Michael James Grant ""Mike"" Ireland",M,36.0,181.0,79.0,Canada,CAN,2010,Vancouver,Speed Skating,Speed Skating Men's 500 metres,NaN
40743,52392,Haley Lyn Irwin,F,21.0,170.0,78.0,Canada,CAN,2010,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22495,75068,Dennis Edward Marineau,M,29.0,172.0,81.0,Canada-2,CAN,1992,Albertville,Bobsleigh,Bobsleigh Men's Two,NaN
22494,74979,Diego Margozzini,M,21.0,182.0,76.0,Chile,CHI,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
22493,74960,Pascal Margerit,M,20.0,180.0,75.0,France,FRA,1992,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
22492,74931,Alexander Marent,M,22.0,168.0,68.0,Austria,AUT,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
21917,53932,Pawe Julian Jaroszek,M,20.0,185.0,82.0,Poland,POL,1992,Albertville,Speed Skating,"Speed Skating Men's 1,500 metres",NaN

## Sorting by multiple values

```dataframe.sort_values(by=["Value 1", "Value 2"], ascending = True)``` for A-Z or smaller numbers to bigger numbers

```ascending = False``` for Z-A or bigger to smaller numbers.

In [12]:
## Sort by values (City and Year) for winter olympics

dfw_city_year_sort = dfw.sort_values(by = ["City", "Year"], ascending = True)

dfw_city_year_sort.head(20)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
20579,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
20580,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
20581,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
20582,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20583,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
20584,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
20585,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
20586,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20587,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
20588,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
20589,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
20590,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Super G,Gold
20591,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze
20592,20,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Norway,NOR,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
20593,367,Masashi Abe,M,26.0,175.0,64.0,Japan,JPN,1992,Albertville,Nordic Combined,Nordic Combined Men's Individual,NaN
20594,415,Bjrn Olof Conny berg,M,23.0,181.0,76.0,Sweden,SWE,1992,Albertville,Freestyle Skiing,Freestyle Skiing Men's Moguls,NaN
20595,422,"Julianne ""Anne"" Abernathy",F,38.0,165.0,75.0,United States Virgin Islands,ISV,1992,Albertville,Luge,Luge Women's Singles,NaN
20596,499,Dany Abounaoum,M,22.0,NaN,NaN,Lebanon,LIB,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
20597,499,Dany Abounaoum,M,22.0,NaN,NaN,Lebanon,LIB,1992,Albertville,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
20598,562,Pawe Abratkiewicz,M,21.0,183.0,84.0,Poland,POL,1992,Albertville,Speed Skating,Speed Skating Men's 500 metres,NaN

In [13]:
## sort by year and then city

dfw_city_year_sort = dfw.sort_values(by = ["Year", "City"], ascending = True)

dfw_city_year_sort.head(20)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver
6,2329,Louis Albert,M,25.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
7,2431,Henri Eugne Aldebert,M,43.0,NaN,NaN,France-1,FRA,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,NaN
8,2902,Karl Ruben Allinger,M,32.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
9,2939,Ernst Alm,M,23.0,174.0,NaN,Sweden,SWE,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze
12,4060,Georges Jules Andr,M,47.0,NaN,NaN,France-1,FRA,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,NaN
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver
14,5429,Karl Wilhelm Konrad Arwe (Andersson-),M,25.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
15,5909,"Frdric ""Fred"" Louis Henri Oscar Auckenthaler",M,24.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
16,5932,Alfred Aufdenblatten,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Gold
17,5932,Alfred Aufdenblatten,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
18,6526,Achille Alberto Bacher,M,23.0,NaN,NaN,Italy,ITA,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN
19,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN

In [55]:
## sort by city and year but descending for summer games

dfw_city_year_sort = dfw.sort_values(by = ["Year", "City"], ascending = False)

dfw_city_year_sort.head(20)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
43678,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Giant Slalom,NaN,winter
43679,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43680,532,Iason Abramashvili,M,25.0,176.0,82.0,Georgia,GEO,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
43681,532,Iason Abramashvili,M,25.0,176.0,82.0,Georgia,GEO,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
43682,534,Oleksandr Volodymyrovych Abramenko,M,25.0,180.0,82.0,Ukraine,UKR,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Aerials,NaN,winter
43683,535,Yevgeny Sergeyevich Abramenko,M,26.0,181.0,80.0,Belarus,BLR,2014,Sochi,Biathlon,Biathlon Men's 10 kilometres Sprint,NaN,winter
43684,535,Yevgeny Sergeyevich Abramenko,M,26.0,181.0,80.0,Belarus,BLR,2014,Sochi,Biathlon,Biathlon Mixed 2 x 6 kilometres and 2 x 7.5 ki...,NaN,winter
43685,535,Yevgeny Sergeyevich Abramenko,M,26.0,181.0,80.0,Belarus,BLR,2014,Sochi,Biathlon,Biathlon Men's 12.5 kilometres Pursuit,NaN,winter
43686,535,Yevgeny Sergeyevich Abramenko,M,26.0,181.0,80.0,Belarus,BLR,2014,Sochi,Biathlon,Biathlon Men's 20 kilometres,NaN,winter
43687,535,Yevgeny Sergeyevich Abramenko,M,26.0,181.0,80.0,Belarus,BLR,2014,Sochi,Biathlon,Biathlon Men's 4 x 7.5 kilometres Relay,NaN,winter
43688,679,Ioan Valeriu Achiriloaie,M,23.0,183.0,87.0,Romania,ROU,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Downhill,NaN,winter
43689,679,Ioan Valeriu Achiriloaie,M,23.0,183.0,87.0,Romania,ROU,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Combined,NaN,winter
43690,753,Yurie Adachi,F,28.0,156.0,51.0,Japan,JPN,2014,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN,winter
43691,840,"Victoria ""Vicki"" Adams",F,24.0,164.0,69.0,Great Britain,GBR,2014,Sochi,Curling,Curling Women's Curling,Bronze,winter
43692,911,Antoine Adelisse,M,17.0,178.0,65.0,France,FRA,2014,Sochi,Freestyle Skiing,Freestyle Skiing Men's Slopestyle,NaN,winter

In [56]:
## you can store into a new df
dfw_city_year_sort = dfw.sort_values(by = ["City", "Year"], ascending=False)

## Please don't open till instructed

### Should Winter and Summer data remain separate?

### What if we want to know total gold medals for any country?

### But if we combine them, how to we easily distinguish between summer and winter?

### Creating a new column with a default value

In [16]:
## In the summer dataframe, add "Season" column with the value "Summer"

dfs ["Season"] = "summer"
dfs

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN,summer
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN,summer
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN,summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
222548,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
222549,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
222550,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [17]:
## In the winter dataframe, add "Season" column with the value "Winter"

dfw ["Season"]="winter"
dfw

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

In [18]:
## are the two column headers identical?

dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
 13  Season        48564 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 5.2 MB

In [62]:
## join winter and summer dataframes together into a dataframe called df

df = pd.concat([dfw,dfs], ignore_index = True)
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
271112,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
271113,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
271114,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [57]:
### confirm that you have the correct number of rows after the join.
### you can scroll up to count the number of entries in oly_w and oly_s.
### The totals should be equal to the value generated below


len(df) == len(dfw) + len(dfs)

True

## Improving memory allocation

If we were working with a massive dataset, we'd want to find ways to improve processing power.

For example, the following columns have only a few values that repeat again and again as strings. This is highly inefficient.

- The "Season" column has "winter" and "summer",
- The "Medal" column only has "gold", "silver" and "bronze",
- "Gender" at this point in the Olympics only has "male" and "female".

One way to improve memory allocation is to take columns with that contain only a few data points and turn them into categories.

In [63]:
## you should see how "Season", "Medal" and "Gender" are all string objects.
## Note that memory usage: 29+ MB

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  str
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: float64(3), int64(2), str(9)
memory usage: 29.0 MB

### Convert to single column to category
```df["column_name"].astype("category")```

In [64]:
## convert gender to category

df["Sex"] = df["Sex"].astype("category")
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
271112,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
271113,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
271114,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [65]:
## INFO

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   str
 13  Season        271116 non-null  str
dtypes: category(1), float64(3), int64(2), str(8)
memory usage: 27.1 MB

### Convert to multiple columns to category

 ```df[["column_name1", "column_name2]].astype("category")```

In [69]:
## convert medal and season  to catagory

df[["Medal", "Season"]] = df[["Medal", "Season"]].astype("category")
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN,summer
271112,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 100 metres,NaN,summer
271113,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 200 metres,NaN,summer
271114,135547,Viktoriya Viktorovna Zyabkina,F,23.0,174.0,62.0,Kazakhstan,KAZ,2016,Rio de Janeiro,Athletics,Athletics Women's 4 x 100 metres Relay,NaN,summer
271115,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer

In [70]:
## See what the memory allocation is now using info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   category
 13  Season        271116 non-null  category
dtypes: category(3), float64(3), int64(2), str(6)
memory usage: 23.5 MB

# It should have dropped to 23.5MB.
That's a big descrease for just about 270,000 rows.

This would have an even bigger impact on larger datasets.

# Query to subset

Create smaller datasets with only the information you want

### Create a subset that holds the results from the Sochi Olympics

```df.query("ColumnName == 'some_value'")```

In [71]:
## return df that holds only Sochi data

df.query("City == 'Sochi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

### Note the order of the single and double quotes:

If you open with double quotes, the inner quotes have to be single quotes:

```df.query("City == 'Sochi'")```

If you open with single quotes, the inner quotes have to be double quotes:

```df.query('City == "Sochi"')```


Using the same outer and inner quotes will break your code:
</br>
```df.query("City == "Sochi"") ## will break ```

In [75]:
## Store subset into dataframe called sochi_df

sochi_df = df.query("City == 'Sochi'")
sochi_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
43673,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
43674,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN,winter
43675,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN,winter
43676,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze,winter
43677,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN,winter
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN,winter
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN,winter
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN,winter

**Syntax for querying multi-word column names:**

```dataframe.query('`column name` comparison_operator value')```

Note the opening and closing tick marks ``` ` ```

In [76]:
#will break

In [79]:
## query to return on french athletes

french_df = df.query("Team == 'France'")
french_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
6,2329,Louis Albert,M,25.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
19,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
20,7343,Klber Balmat,M,27.0,NaN,NaN,France,FRA,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
24,10841,Georges Camille Berthet,M,20.0,NaN,NaN,France,FRA,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Bronze,winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270385,129003,Marie Wattel,F,19.0,181.0,71.0,France,FRA,2016,Rio de Janeiro,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN,summer
270695,132134,Isabelle Yacoubou-Dehoui,F,30.0,190.0,104.0,France,FRA,2016,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,summer
270812,133031,Tony Victor James Yoka,M,24.0,200.0,105.0,France,FRA,2016,Rio de Janeiro,Boxing,Boxing Men's Super-Heavyweight,Gold,summer
270894,133577,Grce Zaadi Deuna,F,23.0,171.0,66.0,France,FRA,2016,Rio de Janeiro,Handball,Handball Women's Handball,Silver,summer
270972,134401,Mickal-Meba Zz,M,22.0,175.0,66.0,France,FRA,2016,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,NaN,summer

## Filtering by dates

You'll learn more about date and time in the coming week. For now, please note how the ```Year``` column is a  ```int64``` object and NOT a ```datetime``` object. We can still work with it for our needs.

In [80]:
## GET INFO

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            271116 non-null  int64
 1   Athlete Name  271116 non-null  str
 2   Sex           271116 non-null  category
 3   Age           261642 non-null  float64
 4   Height        210945 non-null  float64
 5   Weight        208241 non-null  float64
 6   Team          271116 non-null  str
 7   NOC           271116 non-null  str
 8   Year          271116 non-null  int64
 9   City          271116 non-null  str
 10  Sport         271116 non-null  str
 11  Event         271116 non-null  str
 12  Medal         39783 non-null   category
 13  Season        271116 non-null  category
dtypes: category(3), float64(3), int64(2), str(6)
memory usage: 23.5 MB

In [81]:
## Find all the 1900 competitions

competitions_1900 = df.query("Year == 1900")
competitions_1900.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48944,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,summer
48945,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN,summer
48946,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold,summer
48947,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN,summer
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer

In [82]:
### return all the competitions between 1920 and 1950 (inclusive)

competitions_1920_1950 = df.query("1920 <= Year <= 1950")
competitions_1920_1950.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
1,992,Josef Adolf,M,25.0,NaN,NaN,Czechoslovakia,TCH,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter
2,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN,winter
3,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,NaN,winter
4,1077,Xavier Affentranger,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,NaN,winter

In [84]:
## Were there any games in 1950

df_1950 = df[df["Year"] == 1950]
len(df_1950)

0

In [85]:
## return only Tennis competitions between 1920 and 1950 (inclusive)

tennis_1920_1950 = df.query("1920 <= Year <= 1950 and Sport == 'Tennis'")
tennis_1920_1950.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
61094,2302,Pierre Henri Maurice Albarran,M,26.0,NaN,NaN,France-3,FRA,1920,Antwerpen,Tennis,Tennis Men's Doubles,Bronze,summer
61115,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61116,3034,Jos Mara Alonso de Areyzaga,M,30.0,NaN,NaN,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer
61117,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain,ESP,1920,Antwerpen,Tennis,Tennis Men's Singles,NaN,summer
61118,3038,Manuel Alonso de Areyzaga,M,24.0,175.0,66.0,Spain-2,ESP,1920,Antwerpen,Tennis,Tennis Men's Doubles,NaN,summer

In [86]:
## return only Women's Tennis competitions results
## between 1996 and 2018 inclusive

womens_tennis = df.query("1996 <= Year <= 2018 and Sport == 'Tennis' and Sex == 'F'")
womens_tennis.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
190340,4723,Sabine Appelmans (-Haubourdin),F,24.0,169.0,60.0,Belgium,BEL,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer
190341,4723,Sabine Appelmans (-Haubourdin),F,24.0,169.0,60.0,Belgium,BEL,1996,Atlanta,Tennis,Tennis Women's Doubles,NaN,summer
190611,7620,Olga Vladimirovna Barabanshchikova,F,16.0,176.0,60.0,Belarus,BLR,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer
190612,7620,Olga Vladimirovna Barabanshchikova,F,16.0,176.0,60.0,Belarus,BLR,1996,Atlanta,Tennis,Tennis Women's Doubles,NaN,summer
190699,8522,"Nani Rahayu ""Yayuk"" Basuki-Suharyadi",F,25.0,165.0,55.0,Indonesia,INA,1996,Atlanta,Tennis,Tennis Women's Singles,NaN,summer

In [87]:
## volleyball or rowing for only Male

male_volleyball_rowing = df.query("Sport == 'Volleyball' or Sport == 'Rowing' and Sex == 'M'")
male_volleyball_rowing.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
48948,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold,summer
48963,3476,Max Heinrich Ammermann,M,21.0,NaN,NaN,Favorite Hammonia-3,GER,1900,Paris,Rowing,Rowing Men's Coxed Fours,Bronze,summer
48975,4343,Angot,M,NaN,NaN,NaN,Club Nautique de Dieppe-5,FRA,1900,Paris,Rowing,Rowing Men's Coxed Fours,NaN,summer
48980,5538,St George Ashe,M,28.0,NaN,NaN,Great Britain,GBR,1900,Paris,Rowing,Rowing Men's Single Sculls,Bronze,summer
49005,8065,Hermann Joseph Barrelet,M,20.0,NaN,NaN,France,FRA,1900,Paris,Rowing,Rowing Men's Single Sculls,Gold,summer

## What year was women's boxing introduced to the olympics?

In [88]:
## find all the names of sports first just to confirm boxing
## does not appear in different names
## how is boxing listed?

df["Sport"].unique()

<StringArray>
[               'Ice Hockey',           'Nordic Combined',
               'Ski Jumping',      'Cross Country Skiing',
                   'Curling',                 'Bobsleigh',
       'Military Ski Patrol',            'Figure Skating',
             'Speed Skating',                  'Alpinism',
                  'Skeleton',             'Alpine Skiing',
                  'Biathlon',                      'Luge',
          'Freestyle Skiing', 'Short Track Speed Skating',
              'Snowboarding',                    'Tennis',
                 'Athletics',                  'Swimming',
                'Gymnastics',                  'Shooting',
                   'Cycling',                   'Fencing',
             'Weightlifting',                 'Wrestling',
                'Tug-Of-War',                      'Golf',
                    'Rowing',                     'Rugby',
                   'Sailing',                  'Football',
                   'Cricket',                'Water Polo',
             'Equestrianism',                   'Croquet',
                   'Archery',                      'Polo',
             'Basque Pelota',                  'Lacrosse',
                    'Boxing',                    'Diving',
                     'Roque',                    'Hockey',
                  'Racquets',              'Motorboating',
              'Jeu De Paume',          'Art Competitions',
         'Modern Pentathlon',                'Basketball',
                  'Handball',                  'Canoeing',
               'Aeronautics',                'Volleyball',
                      'Judo',       'Rhythmic Gymnastics',
     'Synchronized Swimming',              'Table Tennis',
                 'Badminton',                  'Baseball',
          'Beach Volleyball',                  'Softball',
                 'Taekwondo',                 'Triathlon',
              'Trampolining',              'Rugby Sevens']
Length: 66, dtype: str

### When did boxing first appear as a sport in which women competed at the olympics?

In [89]:
## query for boxing and women
## store in new df

women_boxing = df.query("Sport == 'Boxing' and Sex == 'F'")
women_boxing.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
244598,832,Nicola Virginia Adams,F,29.0,164.0,51.0,Great Britain,GBR,2012,London,Boxing,Boxing Women's Flyweight,Gold,summer
244901,4004,Elizabeth Adhiambo Andiego,F,25.0,172.0,NaN,Kenya,KEN,2012,London,Boxing,Boxing Women's Middleweight,NaN,summer
244966,4859,Adriana dos Santos Arajo,F,30.0,167.0,60.0,Brazil,BRA,2012,London,Boxing,Boxing Women's Lightweight,Bronze,summer
246510,21147,Mavzuna Chorieva,F,19.0,160.0,60.0,Tajikistan,TJK,2012,London,Boxing,Boxing Women's Lightweight,Bronze,summer
247253,29367,Dong Cheng,F,25.0,177.0,60.0,China,CHN,2012,London,Boxing,Boxing Women's Lightweight,NaN,summer

### How many values in a column?

## Counting

- The ```sum``` adds up all the values in a dataset, to give you the total amount.

- The ```count``` tells you how many items of particular values exist in a dataset. It doesn't care about the values themselves, just the number of entries.

We use the ```.value_counts()``` method:

```df_name["column_name"].value_counts()```

### Summer v. Winter

How many athletes participated in the summer games v. the winter games?

In [90]:
## total number of athletes

df["Season"].value_counts()

Season
summer    222552
winter     48564
Name: count, dtype: int64

### ```value_counts()``` parameter

By default, it is ```.value_counts(normalize = False)```

This gives you want we calculated above

But ```.value_counts(normalize = True)``` returns  proportions (fractions of the total).

In [91]:
## get as proportion

df["Season"].value_counts(normalize=True)

Season
summer    0.820874
winter    0.179126
Name: proportion, dtype: float64

In [92]:
## convert to you want it as a percentage

season_percent = df["Season"].value_counts(normalize=True) * 100
season_percent

Season
summer    82.087372
winter    17.912628
Name: proportion, dtype: float64

In [93]:
## subset data to hold only medals

medals_df = df[df["Medal"].notna()]
medals_df.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter

In [94]:
## what is the total medal count for winter v. summer?

medals_df["Season"].value_counts()

Season
summer    34088
winter     5695
Name: count, dtype: int64

# DRY

Do not repeat yourself

In [44]:
##get list of uniques

In [99]:
# target_medals = ["Gold", "Silver", "Bronze"]

medals_df["Medal"].value_counts()

Medal
Gold      13372
Bronze    13295
Silver    13116
Name: count, dtype: int64

In [100]:
## get head
medals_df.head()

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter

In [102]:
## call winners

winners = medals_df
winners.head(50)

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal,Season
0,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
5,1341,Johan Petter hln (Andersson-),M,44.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Curling,Curling Men's Curling,Silver,winter
10,3872,William Harding Anderson,M,22.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
11,4060,Georges Jules Andr,M,47.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
13,5232,Thomas Alfred Arnold,M,22.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter
16,5932,Alfred Aufdenblatten,M,26.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Gold,winter
23,10435,Alfred Berger,M,29.0,NaN,NaN,Austria,AUT,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Gold,winter
24,10841,Georges Camille Berthet,M,20.0,NaN,NaN,France,FRA,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Bronze,winter
40,12565,"Wilhelm Richard ""Willy"" Bckl",M,30.0,NaN,NaN,Austria,AUT,1924,Chamonix,Figure Skating,Figure Skating Men's Singles,Silver,winter
41,13234,Narve Nilsen Bonna,M,23.0,NaN,NaN,Norway,NOR,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",Silver,winter
43,14916,Vin Elias Bremer,M,24.0,NaN,NaN,Finland,FIN,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Silver,winter
44,15400,Ralph Edward Howard Broome,M,34.0,NaN,NaN,Great Britain-1,GBR,1924,Chamonix,Bobsleigh,Bobsleigh Men's Four/Five,Silver,winter
45,15656,Charles Granville Bruce,M,57.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold,winter
46,15659,John Geoffrey Bruce,M,27.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold,winter
48,15774,Pierre mile Ernest Brunet,M,21.0,168.0,NaN,France-1,FRA,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Bronze,winter
50,15776,Andre Marguerite Blanche Brunet-Joly,F,22.0,165.0,NaN,France-1,FRA,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Bronze,winter
55,16457,Tejbir Bura,M,NaN,NaN,NaN,Nepal,NEP,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold,winter
57,17626,"John Archibald ""Jack"" Cameron",M,21.0,NaN,NaN,Canada,CAN,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,winter
58,17919,Pierre Henri Canivet,M,33.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
61,18492,Lorne Howland Carr-Harris,M,24.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
62,18599,Colin Gordon Carruthers,M,33.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
63,18600,Eric Dudley Carruthers,M,28.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
70,21891,"George Eliott ""Guy"" Clarkson",M,33.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
71,22417,"Ernest John ""Ernie"" Collett",M,28.0,NaN,NaN,Canada,CAN,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold,winter
77,23463,Fernand Henri Jean Cournollet,M,41.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
81,23708,Colin Grant Crawford,M,33.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold,winter
82,24452,Cuthbert Ross Cuthbert,M,31.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
102,30131,"Herbert John ""Herb"" Drury",M,27.0,170.0,75.0,United States,USA,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver,winter
107,32641,Helene Engelmann (-Jaroschka),F,25.0,NaN,NaN,Austria,AUT,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Gold,winter
108,33160,"Aku ""August"" Eskelinen",M,25.0,NaN,NaN,Finland,FIN,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Silver,winter
114,35388,George Ingle Finch,M,35.0,NaN,NaN,Australia,AUS,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold,winter
120,39125,Georges Harold Roger Gautschi,M,19.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Figure Skating,Figure Skating Men's Singles,Bronze,winter
136,42258,Gillis Emanuel Grafstrm,M,30.0,NaN,NaN,Sweden,SWE,1924,Chamonix,Figure Skating,Figure Skating Men's Singles,Gold,winter
137,43401,Johan Hagbart Pedersen Grttumsbraaten,M,24.0,180.0,NaN,Norway,NOR,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,Silver,winter
138,43401,Johan Hagbart Pedersen Grttumsbraaten,M,24.0,180.0,NaN,Norway,NOR,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,Bronze,winter
139,43401,Johan Hagbart Pedersen Grttumsbraaten,M,24.0,180.0,NaN,Norway,NOR,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,Bronze,winter
147,46625,Thorleif Haug (Johnsen-),M,29.0,NaN,NaN,Norway,NOR,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 18 kilometres,Gold,winter
148,46625,Thorleif Haug (Johnsen-),M,29.0,NaN,NaN,Norway,NOR,1924,Chamonix,Nordic Combined,Nordic Combined Men's Individual,Gold,winter
149,46625,Thorleif Haug (Johnsen-),M,29.0,NaN,NaN,Norway,NOR,1924,Chamonix,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,Gold,winter
150,46626,Anders Olsen Haugen,M,35.0,179.0,NaN,United States,USA,1924,Chamonix,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",Bronze,winter
162,48837,Heikki Hirvonen,M,28.0,NaN,NaN,Finland,FIN,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Silver,winter
163,49493,Geoffrey Holmes,M,29.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
168,52402,Armand Isaac-Bndic,M,48.0,NaN,NaN,France,FRA,1924,Chamonix,Curling,Curling Men's Curling,Bronze,winter
173,53130,Laurence Jackson,M,23.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Curling,Curling Men's Curling,Gold,winter
174,53154,"William Kilgour ""Willie"" Jackson",M,52.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Curling,Curling Men's Curling,Gold,winter
178,53408,Walter Andreas Jakobsson,M,41.0,174.0,73.0,Finland,FIN,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Silver,winter
179,53409,Ludovika Antje Margareta Jakobsson-Eilers,F,39.0,165.0,58.0,Finland,FIN,1924,Chamonix,Figure Skating,Figure Skating Mixed Pairs,Silver,winter
181,54713,"Charles Henry ""Charley"" Jewtraw",M,23.0,176.0,NaN,United States,USA,1924,Chamonix,Speed Skating,Speed Skating Men's 500 metres,Gold,winter
195,56230,Hamilton Dawson Jukes,M,28.0,NaN,NaN,Great Britain,GBR,1924,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze,winter
196,56238,Alfons Julen,M,24.0,NaN,NaN,Switzerland,SUI,1924,Chamonix,Military Ski Patrol,Military Ski Patrol Men's Military Ski Patrol,Gold,winter

In [48]:
## what is the total medal count for winter v. summer?

## How many medals were handed out at each olympics between 1896 and 2014?

Show the result from highest to lowest.

In [103]:
## how many medals were handed out at each olympics?
## show the result in descending order

medals_by_year = winners.groupby("Year")["Medal"].count().sort_values(ascending=False)
medals_by_year

Year
2008    2048
1992    2030
2016    2023
2000    2004
2004    2001
2012    1941
1988    1845
1996    1842
1984    1698
1980    1602
1976    1531
1972    1414
1920    1308
1968    1256
1964    1215
1960    1058
1956    1043
1952    1033
1936    1025
1948     987
1924     962
1912     941
1908     831
1928     823
1932     739
1900     604
2014     597
2006     526
2010     520
1904     486
2002     478
1906     458
1998     440
1994     331
1896     143
Name: Medal, dtype: int64

In [105]:
## how many medals were handed out at each olympics each
## year from as recent as possible down to 1896.

medals_per_year = winners.groupby("Year")["Medal"].count()

medals_per_year_desc = medals_per_year.sort_index(ascending=False)
medals_per_year_desc

Year
2016    2023
2014     597
2012    1941
2010     520
2008    2048
2006     526
2004    2001
2002     478
2000    2004
1998     440
1996    1842
1994     331
1992    2030
1988    1845
1984    1698
1980    1602
1976    1531
1972    1414
1968    1256
1964    1215
1960    1058
1956    1043
1952    1033
1948     987
1936    1025
1932     739
1928     823
1924     962
1920    1308
1912     941
1908     831
1906     458
1904     486
1900     604
1896     143
Name: Medal, dtype: int64

In [108]:
## top 10 count of gold medals by country
gold_winners = winners[winners["Medal"] == "Gold"]
gold_counts = gold_winners["Team"].value_counts()
top10_gold = gold_counts.head(10)
top10_gold

Team
United States    2474
Soviet Union     1058
Germany           679
Italy             535
Great Britain     519
France            455
Sweden            451
Hungary           432
Canada            422
East Germany      369
Name: count, dtype: int64

In [109]:
## count of gold medals by country by percent
## only gold winner df
gold_percent = gold_winners["Team"].value_counts(normalize=True) * 100
gold_percent

Team
United States    18.501346
Soviet Union      7.912055
Germany           5.077774
Italy             4.000897
Great Britain     3.881244
                   ...
Bahrain           0.007478
Kosovo            0.007478
Tajikistan        0.007478
Puerto Rico       0.007478
Singapore         0.007478
Name: proportion, Length: 242, dtype: float64

In [53]:
## as percent

In [110]:
## how many times did Russia win the gold?
gold_winners["Team"].value_counts().get("Russia", 0)

np.int64(366)